using Content.Shared.CCVar;
using Content.Shared._Starlight.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Prototypes;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MiscTab : Control
{
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public MiscTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Starlight-edit: themes/layout moved to UI tab.

        // Channel can be null in replays so.
        // ReSharper disable once ConditionalAccessQualifierIsNonNullableAccordingToAPIContract
        ShowOocPatronColor.Visible = _playerManager.LocalSession?.Channel?.UserData.PatronTier is { };

        // Starlight-edit: themes/layout moved to UI tab.

        Control.AddOptionCheckBox(CVars.DiscordEnabled, DiscordRich);
        Control.AddOptionCheckBox(CCVars.ShowOocPatronColor, ShowOocPatronColor);
        Control.AddOptionCheckBox(CCVars.LoocAboveHeadShow, ShowLoocAboveHeadCheckBox);
        Control.AddOptionCheckBox(CCVars.HudHeldItemShow, ShowHeldItemCheckBox);
        Control.AddOptionCheckBox(CCVars.CombatModeIndicatorsPointShow, ShowCombatModeIndicatorsCheckBox);
        Control.AddOptionCheckBox(CCVars.OpaqueStorageWindow, OpaqueStorageWindowCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatEnableFancyBubbles, FancySpeechBubblesCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatFancyNameBackground, FancyNameBackgroundsCheckBox);
        var chatTranslateEntries = new List<OptionDropDownCVar<string>.ValueOption>
        {
            new("auto", Loc.GetString("ui-options-chat-translate-auto")),
            new("es", Loc.GetString("ui-options-chat-translate-es")),
            new("en", Loc.GetString("ui-options-chat-translate-en")),
            new("bilingual", Loc.GetString("ui-options-chat-translate-bilingual")),
            new("off", Loc.GetString("ui-options-chat-translate-off")),
        };
        Control.AddOptionDropDown(CCVars.NixChatTranslateTarget, DropDownChatTranslate, chatTranslateEntries); // Nix
        Control.AddOptionCheckBox(CCVars.StaticStorageUI, StaticStorageUI);
        // Starlight-start
        Control.AddOptionCheckBox(StarlightCCVars.AutoPunctuate, AutoPunctuate);
        Control.AddOptionCheckBox(StarlightCCVars.WieldBeforeRack, WieldBeforeRack);
        Control.AddOptionCheckBox(StarlightCCVars.ForceTestersTab, ForceTestersTab);
        // Starlight-end

        Control.Initialize();
    }
}
