using Content.Shared._Nix.Traits.Musician;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Nix.Traits.Musician;

[GenerateTypedNameReferences]
public sealed partial class MusicianChoiceBoxWindow : DefaultWindow
{
    public event Action<string>? OnInstrumentSelected;

    private readonly List<string> _instrumentIds = new();

    public MusicianChoiceBoxWindow()
    {
        RobustXamlLoader.Load(this);

        InstrumentOption.OnItemSelected += args =>
        {
            InstrumentOption.SelectId(args.Id);
        };

        CancelButton.OnPressed += _ => Close();

        OkButton.OnPressed += _ =>
        {
            if (InstrumentOption.SelectedId >= 0 && InstrumentOption.SelectedId < _instrumentIds.Count)
            {
                OnInstrumentSelected?.Invoke(_instrumentIds[InstrumentOption.SelectedId]);
                Close();
            }
        };
    }

    public void Populate(Dictionary<string, string> instruments)
    {
        InstrumentOption.Clear();
        _instrumentIds.Clear();

        var index = 0;
        foreach (var (id, name) in instruments)
        {
            _instrumentIds.Add(id);
            InstrumentOption.AddItem(name, index);
            index++;
        }

        if (_instrumentIds.Count > 0)
        {
            InstrumentOption.SelectId(0);
        }
    }
}
