using Content.Client.Players.PlayTimeTracking;
using Content.Shared._Starlight.Traits;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.Traits.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitEntry : PanelContainer
{
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private JobRequirementsManager _requirementsManager = default!;

    public event Action<bool>? OnToggled;

    public bool IsSelected => TraitCheckbox.Pressed;
    public readonly int TraitCost;
    public bool MeetsConditions { get; private set; } = true;

    private readonly TraitPrototype _trait;
    private bool _isUpdating;
    private FormattedMessage _requirements = new();

    public TraitEntry(TraitPrototype trait)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _trait = trait;
        TraitCost = trait.Cost;

        // Enable mouse events so tooltips work
        MouseFilter = MouseFilterMode.Pass;

        TraitNameLabel.Text = Loc.GetString(trait.Name);
        TraitDescriptionLabel.SetMessage(Loc.GetString(trait.Description));

        // Format cost display: negative cost means it gives points (+ in green), positive cost means it spends points (- in red)
        string costText;
        string costColor;
        if (trait.Cost < 0)
        {
            costText = $"+{-trait.Cost}";
            costColor = "#6bff6b";
        }
        else if (trait.Cost > 0)
        {
            costText = $"-{trait.Cost}";
            costColor = "#ff6b6b";
        }
        else
        {
            costText = "0";
            costColor = "#888888";
        }

        TraitCostLabel.Text = costText;
        TraitCostLabel.ModulateSelfOverride = Color.FromHex(costColor);

        TraitCheckbox.OnToggled += OnCheckboxToggled;
    }

    /// <summary>
    /// Updates whether conditions are met based on current job/species.
    /// </summary>
    public void UpdateConditionsMet(HumanoidCharacterProfile? profile)
    {
        MeetsConditions = true;

        if (!_requirementsManager.CheckRequirementsForNonRole(_trait.Requirements, _playerManager.LocalSession, profile, out var reason))
        {
            MeetsConditions = false;
            if (reason is not null)
                _requirements = reason;
        }

        UpdateDisabledState();
    }

    private void UpdateDisabledState()
    {
        if (!MeetsConditions)
        {
            // Hide checkbox, show lock icon
            TraitCheckbox.Visible = false;
            LockIcon.Visible = true;

            // Deselect if conditions no longer met
            if (TraitCheckbox.Pressed)
            {
                _isUpdating = true;
                TraitCheckbox.Pressed = false;
                UpdateSelectedStyle();
                _isUpdating = false;
                OnToggled?.Invoke(false);
            }

            // Add disabled styling
            AddStyleClass("TraitsEntryDisabled");

            // Update tooltip to show failed requirements
            var tooltip = new Tooltip();
            tooltip.SetMessage(_requirements);
            TraitPanel.TooltipSupplier = _ => tooltip;
        }
        else
        {
            // Show checkbox, hide lock icon
            TraitCheckbox.Visible = true;
            LockIcon.Visible = false;

            // Remove disabled styling - stylesheet restores normal colors
            RemoveStyleClass("TraitsEntryDisabled");
        }
    }

    private void OnCheckboxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        if (_isUpdating)
            return;

        if (!MeetsConditions)
        {
            // This shouldn't happen since checkbox is hidden, but just in case
            _isUpdating = true;
            TraitCheckbox.Pressed = false;
            _isUpdating = false;
            return;
        }

        UpdateSelectedStyle();
        OnToggled?.Invoke(args.Pressed);
    }

    public void SetSelected(bool selected)
    {
        _isUpdating = true;
        TraitCheckbox.Pressed = selected && MeetsConditions;
        UpdateSelectedStyle();
        _isUpdating = false;
    }

    private void UpdateSelectedStyle()
    {
        if (TraitCheckbox.Pressed)
            AddStyleClass("TraitsEntrySelected");
        else
            RemoveStyleClass("TraitsEntrySelected");
    }
}
