using System;
using Content.Client.Administration.Systems;
using Content.Shared._Nix.Administration;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
        public sealed partial class AdminShuttleWindow : DefaultWindow
        {
        [Dependency] private IEntityManager _entityManager = default!;
        private readonly AdminSystem _adminSystem;
        private readonly List<string> _shuttlePaths = new();
        private string? _selectedShuttlePath;
        private bool _selectionLocked;

        public AdminShuttleWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _adminSystem = _entityManager.System<AdminSystem>();

            _callShuttleTime.OnTextChanged += CallShuttleTimeOnOnTextChanged;
            _callShuttleButton.OnPressed += _ => CallShuttle();
            _recallShuttleButton.OnPressed += _ =>
                _adminSystem.SendNixAdminShuttleCommand(NixAdminShuttleAction.Recall);
            _shuttleOption.OnItemSelected += args =>
            {
                _shuttleOption.SelectId(args.Id);
                _selectedShuttlePath = args.Id >= 0 && args.Id < _shuttlePaths.Count
                    ? _shuttlePaths[args.Id]
                    : null;
                _selectShuttleButton.Disabled = _selectionLocked || _selectedShuttlePath == null;
            };
            _selectShuttleButton.OnPressed += _ => SelectShuttle();
            _applyPurchaseLockButton.OnPressed += _ =>
                _adminSystem.SendNixAdminShuttleCommand(
                    NixAdminShuttleAction.SetPurchaseLock,
                    locked: _purchaseLockCheckBox.Pressed);

            _adminSystem.NixAdminShuttleSnapshot += OnSnapshot;
            _adminSystem.NixAdminShuttleResult += OnResult;
            _adminSystem.RequestNixAdminShuttle();
            _selectShuttleButton.Disabled = true;
        }

        private void CallShuttleTimeOnOnTextChanged(LineEdit.LineEditEventArgs obj)
        {
            var loc = IoCManager.Resolve<ILocalizationManager>();
            _callShuttleButton.Disabled = !TimeSpan.TryParseExact(obj.Text, ContentLocalizationManager.TimeSpanMinutesFormats, loc.DefaultCulture, out _);
        }

        private void CallShuttle()
        {
            var loc = IoCManager.Resolve<ILocalizationManager>();
            if (!TimeSpan.TryParseExact(_callShuttleTime.Text, ContentLocalizationManager.TimeSpanMinutesFormats, loc.DefaultCulture, out var time))
                return;

            _adminSystem.SendNixAdminShuttleCommand(NixAdminShuttleAction.Call, (float) time.TotalSeconds);
        }

        private void SelectShuttle()
        {
            if (_selectedShuttlePath == null)
                return;

            _adminSystem.SendNixAdminShuttleCommand(
                NixAdminShuttleAction.SelectEmergencyShuttle,
                shuttlePath: _selectedShuttlePath);
        }

        private void OnSnapshot(NixAdminShuttleSnapshotEvent snapshot)
        {
            _stateLabel.Text = Loc.GetString(snapshot.Called
                ? "admin-shuttle-state-called"
                : "admin-shuttle-state-idle", ("seconds", MathF.Ceiling(snapshot.SecondsRemaining)));
            _callShuttleButton.Disabled = snapshot.Called;
            _recallShuttleButton.Disabled = !snapshot.Called;
            _purchaseLockCheckBox.Pressed = snapshot.PurchasesLocked;
            _selectionLocked = snapshot.SelectionLocked;
            _currentShuttleLabel.Text = Loc.GetString("admin-shuttle-current",
                ("shuttle", DisplayName(snapshot.CurrentShuttlePath)));

            _shuttlePaths.Clear();
            _shuttlePaths.AddRange(snapshot.AvailableShuttles);
            _shuttleOption.Clear();
            foreach (var path in _shuttlePaths)
                _shuttleOption.AddItem(DisplayName(path));
            _selectedShuttlePath = null;
            _selectShuttleButton.Disabled = true;
        }

        private void OnResult(NixAdminShuttleResultEvent result)
        {
            _statusLabel.Text = Loc.GetString(result.Success
                ? "admin-shuttle-action-success"
                : "admin-shuttle-action-failed");
        }

        private static string DisplayName(string path)
        {
            var slash = path.LastIndexOf('/');
            var name = slash >= 0 ? path[(slash + 1)..] : path;
            return name.EndsWith(".yml", StringComparison.OrdinalIgnoreCase) ? name[..^4] : name;
        }

        protected override void Dispose(bool disposing)
        {
            _adminSystem.NixAdminShuttleSnapshot -= OnSnapshot;
            _adminSystem.NixAdminShuttleResult -= OnResult;
            base.Dispose(disposing);
        }
    }
}
