- type: jobRequirementOverride
  id: Reduced
  jobs:
    Captain:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 6h # Starlight
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 6h # Starlight
    - !type:DepartmentTimeRequirement
      department: Security
      time: 6h # Starlight
# Starlight start
    - !type:DepartmentTimeRequirement
      department: Science
      time: 6h
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 6h
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 6h
# Starlight end
    - !type:DepartmentTimeRequirement
      department: Command
      time: 10h # Starlight
# Starlight start
    - !type:OverallPlaytimeRequirement
      time: 10h
    - !type:RoleTimeRequirement
      role: JobStationAi
      time: 1h
    HeadOfPersonnel:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Science
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 5h
    - !type:OverallPlaytimeRequirement
      time: 7h
    HeadOfSecurity:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 8h
    ChiefEngineer:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 3h
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 3h
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 1h
    ResearchDirector:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 3h
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:RoleTimeRequirement
      role: JobScientist
      time: 1h
    ChiefMedicalOfficer:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3h
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 1h
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 1h
    Quartermaster:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 3h
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 1h
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 2h
    MedicalDoctor:
    - !type:OverallPlaytimeRequirement
      time: 0
    Chemist:
    - !type:OverallPlaytimeRequirement
      time: 0
    Paramedic:
    - !type:OverallPlaytimeRequirement
      time: 0
    Psychologist:
    - !type:OverallPlaytimeRequirement
      time: 0
    Surgeon:
    - !type:OverallPlaytimeRequirement
      time: 0
    Roboticist:
    - !type:OverallPlaytimeRequirement
      time: 0
    StationEngineer:
    - !type:OverallPlaytimeRequirement
      time: 0
    AtmosphericTechnician:
    - !type:OverallPlaytimeRequirement
      time: 0
    MiningSpecialist:
    - !type:OverallPlaytimeRequirement
      time: 0
    SalvageSpecialist:
    - !type:OverallPlaytimeRequirement
      time: 0
    SalvageLead:
    - !type:OverallPlaytimeRequirement
      time: 0
    Warden:
    - !type:OverallPlaytimeRequirement
      time: 0
    DutyOfficer:
    - !type:OverallPlaytimeRequirement
      time: 0
    SecurityCadet:
    - !type:OverallPlaytimeRequirement
      time: 30h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 30h #SL Edit 15h -> 30h
      inverted: true # stop playing intern if you're good at security!
    SecurityOfficer:
    - !type:OverallPlaytimeRequirement
      time: 0
    Detective:
    - !type:OverallPlaytimeRequirement
      time: 0
    Brigmedic:
    - !type:OverallPlaytimeRequirement
      time: 0
    K9:
    - !type:OverallPlaytimeRequirement
      time: 0
    StationAi:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobBorg
      time: 3h
    Borg:
    - !type:OverallPlaytimeRequirement
      time: 1h
    Bartender:
    - !type:OverallPlaytimeRequirement
      time: 0
    Chef:
    - !type:OverallPlaytimeRequirement
      time: 0
    Scientist:
    - !type:OverallPlaytimeRequirement
      time: 0
    Botanist:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobServiceWorker
      time: 20m
    Clown:
    - !type:OverallPlaytimeRequirement
      time: 0
    - !type:RoleTimeRequirement
      role: JobPassenger
      time: 10m
    CargoTechnician:
    - !type:OverallPlaytimeRequirement
      time: 0
    TechnicalAssistant:
    - !type:OverallPlaytimeRequirement
      time: 5m
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 25h #SL edit 15 -> 25
      inverted: true
    MedicalIntern:
    - !type:OverallPlaytimeRequirement
      time: 5m
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 25h #SL edit 15 -> 25
      inverted: true
    ResearchAssistant:
    - !type:OverallPlaytimeRequirement
      time: 5m
    - !type:DepartmentTimeRequirement
      department: Science
      time: 25h #SL edit 15 -> 25
      inverted: true
    Chaplain:
    - !type:OverallPlaytimeRequirement
      time: 0
    Janitor:
    - !type:OverallPlaytimeRequirement
      time: 0
    Lawyer:
    - !type:OverallPlaytimeRequirement
      time: 0
    Librarian:
    - !type:OverallPlaytimeRequirement
      time: 0
    Mime:
    - !type:OverallPlaytimeRequirement
      time: 0
    Musician:
    - !type:OverallPlaytimeRequirement
      time: 0
    ServiceWorker:
    - !type:OverallPlaytimeRequirement
      time: 0
    Performer:
    - !type:OverallPlaytimeRequirement
      time: 0
    Visitor:
    - !type:OverallPlaytimeRequirement
      time: 0
# Starlight end
