using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class RoundTab : Control
    {
        [Dependency] private readonly IClientConsoleHost _console = default!;

        private static readonly (string Name, string Id)[] Presets =
        [
            ("Secreto (Secret)", "secret"),
            ("Traidores (Traitor)", "traitor"),
            ("Revolución (Revolution)", "revolution"),
            ("Operativos Nucleares (Nukeops)", "nukeops"),
            ("Zombis / Infección (Zombie)", "zombie"),
            ("Vampiros (Vampire)", "vampire"),
            ("Mago Espacial (Wizard)", "wizard"),
            ("Extendido / Sandbox (Extended)", "extended"),
            ("Supervivencia (Survival)", "survival"),
            ("Comedia de Payasos (Clown)", "clown"),
            ("Guerra de Sindicato (War)", "war")
        ];

        private int _selectedPresetIndex;

        public RoundTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            StartRound.OnPressed += _ => _console.ExecuteCommand("startround");
            EndRound.OnPressed += _ => _console.ExecuteCommand("endround");
            RestartRound.OnPressed += _ => _console.ExecuteCommand("restartround");
            RestartRoundNow.OnPressed += _ => _console.ExecuteCommand("restartroundnow");
            DelayRound.OnPressed += _ => DelayRoundStart();
            PauseRound.OnPressed += _ =>
            {
                _console.ExecuteCommand("delaystart -1");
                DelayStatusLabel.Text = Loc.GetString("administration-ui-round-tab-status-paused");
            };
            ResumeRound.OnPressed += _ =>
            {
                _console.ExecuteCommand("delaystart 0");
                DelayStatusLabel.Text = Loc.GetString("administration-ui-round-tab-status-resumed");
            };

            GamePresetOption.OnItemSelected += args =>
            {
                GamePresetOption.SelectId(args.Id);
                _selectedPresetIndex = args.Id;
                SetGamePresetButton.Disabled = false;
            };

            SetGamePresetButton.OnPressed += _ => ApplyGamePreset();

            PopulateGamePresets();
        }

        private void PopulateGamePresets()
        {
            GamePresetOption.Clear();

            for (var i = 0; i < Presets.Length; i++)
            {
                var (name, id) = Presets[i];
                GamePresetOption.AddItem($"{name} ({id})", i);
            }

            if (Presets.Length > 0)
            {
                GamePresetOption.SelectId(0);
                _selectedPresetIndex = 0;
                SetGamePresetButton.Disabled = false;
            }
        }

        private void ApplyGamePreset()
        {
            if (_selectedPresetIndex < 0 || _selectedPresetIndex >= Presets.Length)
                return;

            var (name, id) = Presets[_selectedPresetIndex];
            _console.ExecuteCommand($"setgamepreset {id}");
            GamePresetStatusLabel.Text = Loc.GetString("administration-ui-round-tab-mode-applied",
                ("mode", name),
                ("id", id));
        }

        private void DelayRoundStart()
        {
            if (!uint.TryParse(DelayMinutesLineEdit.Text, out var minutes) || minutes is 0 or > 1440)
            {
                DelayStatusLabel.Text = Loc.GetString("administration-ui-round-tab-delay-invalid");
                return;
            }

            _console.ExecuteCommand($"delaystart {minutes * 60}");
            DelayStatusLabel.Text = Loc.GetString("administration-ui-round-tab-status-delayed",
                ("minutes", minutes));
        }
    }
}
