using Content.Client.Administration.Managers;
using Content.Client.Administration.Systems;
using Content.Client.UserInterface.Systems.DecalPlacer;
using Content.Shared.Administration;
using Content.Shared._Nix.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Upload.Commands;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controllers.Implementations;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.AdminbusTab
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminbusTab : Control
    {
        private readonly EntitySpawningUIController _entitySpawningController;
        private readonly TileSpawningUIController _tileSpawningController;
        private readonly DecalPlacerUIController _decalPlacerController;
        private readonly AdminSystem _adminSystem;

        [Dependency] private IEntityManager _entityManager = default!;

        public AdminbusTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _entitySpawningController = UserInterfaceManager.GetUIController<EntitySpawningUIController>();
            _tileSpawningController = UserInterfaceManager.GetUIController<TileSpawningUIController>();
            _decalPlacerController = UserInterfaceManager.GetUIController<DecalPlacerUIController>();
            _adminSystem = _entityManager.System<AdminSystem>();
            _adminSystem.NixAdminPowerResult += OnPowerResult;

            var adminManager = IoCManager.Resolve<IClientAdminManager>();
            adminManager.AdminStatusUpdated += OnStatusUpdate;

            // For the SpawnEntitiesButton and SpawnTilesButton we need to do the press manually
            // TODO: This will probably need some command check at some point
            SpawnEntitiesButton.OnPressed += SpawnEntitiesButtonOnPressed;
            SpawnTilesButton.OnPressed += SpawnTilesButtonOnOnPressed;
            SpawnDecalsButton.OnPressed += SpawnDecalsButtonOnPressed;
            LoadGamePrototypeButton.OnPressed += LoadGamePrototypeButtonOnPressed;
            LoadGamePrototypeButton.Disabled = !adminManager.CanCommand("loadprototype");
            LoadBlueprintsButton.Disabled = !adminManager.CanCommand("loadgrid");
            RechargeSmesButton.OnPressed += _ =>
                _adminSystem.SendNixAdminPowerCommand(NixAdminPowerAction.RechargeSmes);
            RestoreStationApcsButton.OnPressed += _ =>
                _adminSystem.SendNixAdminPowerCommand(NixAdminPowerAction.RestoreStationApcs);
        }

        private void OnStatusUpdate()
        {
            var adminManager = IoCManager.Resolve<IClientAdminManager>();
            LoadGamePrototypeButton.Disabled = !adminManager.CanCommand("loadprototype");
            LoadBlueprintsButton.Disabled = !adminManager.CanCommand("loadgrid");
        }

        private void LoadGamePrototypeButtonOnPressed(BaseButton.ButtonEventArgs obj)
        {
            LoadPrototypeCommand.LoadPrototype();
        }

        private void SpawnEntitiesButtonOnPressed(BaseButton.ButtonEventArgs obj)
        {
            _entitySpawningController.ToggleWindow();
        }

        private void SpawnTilesButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
        {
            _tileSpawningController.ToggleWindow();
        }

        private void SpawnDecalsButtonOnPressed(BaseButton.ButtonEventArgs obj)
        {
            _decalPlacerController.ToggleWindow();
        }

        private void OnPowerResult(NixAdminPowerResultEvent result)
        {
            var key = result.Action == NixAdminPowerAction.RechargeSmes
                ? "administration-ui-adminbus-recharge-smes-result"
                : "administration-ui-adminbus-restore-apcs-result";
            PowerResultLabel.Text = Loc.GetString(key, ("count", result.AffectedCount));
        }

        protected override void Dispose(bool disposing)
        {
            _adminSystem.NixAdminPowerResult -= OnPowerResult;
            base.Dispose(disposing);
        }
    }
}
